import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../hooks/useAuth";
import { getUserGeneratedRecipes } from "../services/RecipesService";
import { handleApiError } from "../utils/error-handler";
import { getGeneratedRecipes as getStoredRecipes } from "../utils/generatedRecipesStorage";
import RecipeCard from "../components/RecipeCard/RecipeCard";
import PacmanLoading from "../components/PacmanLoading/PacmanLoading";
import { Alert, Button } from "react-bootstrap";
import { useNavigate } from "react-router-dom";
import "../index.css";

/**
 * GeneratedRecipes Page Component
 * Displays recipes generated by the authenticated user.
 * Follows Single Responsibility: handles display of user-generated recipes.
 */
const GeneratedRecipes = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [recipes, setRecipes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [showScroll, setShowScroll] = useState(false);

  /**
   * Fetches user's generated recipes from the API.
   */
  useEffect(() => {
    if (!user) {
      setLoading(false);
      return;
    }

    const fetchRecipes = async () => {
      try {
        setLoading(true);
        setError(null);
        
        try {
          const userRecipes = await getUserGeneratedRecipes();
          const backendRecipes = Array.isArray(userRecipes) ? userRecipes : [];
          
          if (backendRecipes.length > 0) {
            setRecipes(backendRecipes);
            return;
          }
        } catch (err) {
          if (err?.response?.status === 404) {
            console.log("Backend endpoint not available, using localStorage fallback");
          } else {
            const errorMessage = handleApiError(err, "Generated Recipes");
            setError(errorMessage);
          }
        }
        
        const storedRecipes = getStoredRecipes();
        if (storedRecipes.length > 0) {
          setRecipes(storedRecipes);
          setError(null);
        } else {
          setRecipes([]);
        }
      } catch (err) {
        const errorMessage = handleApiError(err, "Generated Recipes");
        setError(errorMessage);
        setRecipes([]);
      } finally {
        setLoading(false);
      }
    };

    fetchRecipes();
  }, [user]);

  /**
   * Handles scroll to show/hide scroll-to-top button.
   */
  useEffect(() => {
    const handleScroll = () => {
      setShowScroll(window.scrollY > 300);
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  /**
   * Scrolls to top of page smoothly.
   */
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  if (!user) {
    return (
      <div className="container mt-5 text-center">
        <Alert variant="warning">
          <Alert.Heading>Acceso restringido</Alert.Heading>
          <p>Debes iniciar sesión para ver tus recetas generadas.</p>
          <Button variant="primary" onClick={() => navigate("/login")}>
            Iniciar Sesión
          </Button>
        </Alert>
      </div>
    );
  }

  if (loading) {
    return (
      <div
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "100vh",
        }}
      >
        <PacmanLoading />
      </div>
    );
  }

  return (
    <div className="container mt-5">
      <div className="row mb-4">
        <div className="col-12 text-center">
          <h1 className="h2 mb-3" style={{ color: "#83a580" }}>
            <i className="fa-solid fa-wand-magic-sparkles me-2"></i>
            Mis Recetas Generadas
          </h1>
          <p className="text-muted">
            Recetas personalizadas creadas especialmente para ti
          </p>
        </div>
      </div>

      {error && (
        <Alert variant="danger" dismissible onClose={() => setError(null)} className="mb-4">
          <Alert.Heading>Error al cargar recetas</Alert.Heading>
          <p>{error}</p>
        </Alert>
      )}

      {recipes.length > 0 ? (
        <>
          <div className="row mb-3">
            <div className="col-12 text-end">
              <span className="badge bg-success fs-6">
                {recipes.length} {recipes.length === 1 ? "receta" : "recetas"}
              </span>
            </div>
          </div>

          <div className="row">
            {recipes.map((recipe) => (
              <div key={recipe._id} className="col-12 col-md-6 col-lg-4 mb-4">
                <RecipeCard recipe={recipe} />
              </div>
            ))}
          </div>
        </>
      ) : (
        <div className="text-center mt-5 py-5">
          <div className="mb-4">
            <i className="fa-solid fa-utensils" style={{ fontSize: "4rem", color: "#83a580", opacity: 0.5 }}></i>
          </div>
          <h3 className="h4 mb-3">Aún no has generado recetas</h3>
          <p className="text-muted mb-4">
            Crea recetas personalizadas eligiendo tus ingredientes favoritos
          </p>
          <Button
            variant="primary"
            className="btn-custom"
            onClick={() => navigate("/")}
          >
            <i className="fa-solid fa-plus me-2"></i>
            Generar Recetas
          </Button>
        </div>
      )}

      <button
        className={`scroll-to-top ${showScroll ? "show" : ""}`}
        onClick={scrollToTop}
        aria-label="Volver arriba"
      >
        <i className="fa-solid fa-arrow-up"></i>
      </button>
    </div>
  );
};

export default GeneratedRecipes;

